### PR TITLE
FEAT : Implementation of Turtle Boss

### PR DESCRIPTION
**Pull request by this-yujunkim**
## What
This PR adds the Turtle type boss.
- Added Turtle sprite to `spriteMap` in `DrawManager.java`.
- Added Turtle's reflection gimmick very briefly.

## ~~Some Major Changes To Check~~
~~Plaese note that GameSettings now has parameter `String bossType` not `boolean isBossLevel` to check current Boss type. `bossType` is set `null` in normal levels. But `isBossLevel()`will work just as usual.
I know there will be conflict with  #51 but I think #51 's method is better at telling the difference between bosses. So lets talk about this and work on that next week.~~

## New Changes
All conflicts have been solved yesterday(2024.11.18) and decided to follow #51 's idea of implementing various boss'.

### CODE REVIEW

**Comment by HSHyun** [comment]
좋아요 거북이 스프라이트가 잘 추가 되었고, 짧지만 기믹 추가도 좋은것 같습니다.

**Review by HSHyun — APPROVED** [review]
좋아요 거북이 스프라이트가 잘 추가 되었고, 짧지만 기믹 추가도 좋은것 같습니다.

**Comment by this-yujunkim** [comment]
All conflicts have been solved and checked yesterday(2024.11.18) and decided to follow https://github.com/Dream-no24/PlayerEnemyShipVariety/pull/51 's idea of implementing various boss'. 
Since github-action requested review again, the number of reviewers became three. So I've deleted new reviewer by hand.

**Review by depave — COMMENTED** [review]
line 721 of GameScreen. I changed int feverScore = CntAndPnt[0]; to int feverScore = bossParts.getPointValue(); , beacuse of this line makes score issue that the result screen score does not match the score obtained.
Is this issue okay with this PR?

**Pull request closed without merging**
